name: Auto-label PRs by Commit Message

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Auto-label using commit messages
        uses: tj-actions/auto-assign-issue-label@v2
        with:
          include-commit-message: true
          commit-message-regex-labels: |
            ^feat:.*=feature
            ^fix:.*=fix
            ^chore:.*=chore
            ^docs:.*=documentation
            ^refactor:.*=refactor
