name: Auto Label PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: ahmadnassri/action-conventional-commit-labels@v2
