name: Label Pull Requests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Labels
        uses: mauroalderete/action-assign-labels@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'bug, enhancement, feature, hotfix'
