name: Label Pull Requests Based on Conventional Commits

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Labels from Conventional Commits
        uses: mauroalderete/action-assign-labels@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          apply-changes: true
          conventional-commits: |
            conventional-commits:
              - type: 'fix'
                nouns: ['fix', 'fixed']
                labels: ['bug']
              - type: 'feat'
                nouns: ['feat', 'feature']
                labels: ['enhancement']
              - type: 'chore'
                nouns: ['chore']
                labels: ['maintenance']
              - type: 'docs'
                nouns: ['docs']
                labels: ['documentation']
              - type: 'refactor'
                nouns: ['refactor']
                labels: ['refactoring']
              - type: 'test'
                nouns: ['test']
                labels: ['testing']
              - type: 'BREAKING CHANGE'
                nouns: ['BREAKING CHANGE']
                labels: ['breaking change']
